# Generated by Django 5.1.5 on 2025-01-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_house_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='ward_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
