# Generated by Django 5.1.5 on 2025-02-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_custom_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visithistory',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
