# Generated by Django 5.1.5 on 2025-02-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_visithistory_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='visithistory',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
    ]
