# Generated by Django 5.1.5 on 2025-01-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ward_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
