# Generated by Django 5.1.5 on 2025-01-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_ward_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
