# Generated by Django 5.1.5 on 2025-02-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_product_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='product_info',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='user',
            name='product_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
